services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ../k6:/scripts
    environment:
      - BASE_URL=http://host-docker-internal:8080
    extra_hosts:
      - "host-docker-internal:host-gateway"
    command: run /scripts/product-list.js
